name: Math Utility Repo applying CI    #Tên của nhóm cv cần phải làm khi ai đó push code

on:
  push:
    branches: [ "main" ]  # Bất kỳ khi nào mà ai đó push code lên nhánh main 
  pull_request:
    branches: [ "main" ]

jobs:                   # thì làm các việc ở dưới đây
  build:

    runs-on: ubuntu-latest    #1. mượn 1 cái server của Mỹ, cài sẵn hệ điều hành Ubuntu

    steps:                        #2. Làm thêm các bước sau trên server vừa mượn
    - uses: actions/checkout@v3   #2.1: Lấy toàn bộ code từ kho chuyển sang server
    - name: Set up JDK 18         #2.2 Mượn JDK nào đó trên server , 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven      #2.3: chuẩn bị chạy lệnh build app, chạy lun unit test nếu có
      run: mvn -B package --file pom.xml

    - name: Distribute jar-war file # Gửi file .jar .war đi đâu, CD nhảy vào ...
      run: mkdir staging && cp target/*.jar staging # tạo thư mục staging chứa file .jar .war sau khi build      
     
    - name: Make hyperlink to jar-war file # Tạo hyperlink để download build 
      uses: actions/upload-artifact@v1
      with:
          name: HAY-DOWN-EM-JAR-O-DAY   # Bản build .JAR/.WAR được nén ở link kế bên
          path: staging
